package tmpl

const NotEditMark = `
// Code generated by github.com/yunboom/generate. DO NOT EDIT.
// Code generated by github.com/yunboom/generate. DO NOT EDIT.
// Code generated by github.com/yunboom/generate. DO NOT EDIT.
`

const HeaderTmpl = NotEditMark + `
package {{.}}

import(
	"database/sql"

	"github.com/jinzhu/gorm"
	"github.com/jinzhu/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"
)
`
