package template

const NotEditMark = `
// Code generated by generate. DO NOT EDIT.
// Code generated by generate. DO NOT EDIT.
// Code generated by generate. DO NOT EDIT.
`

const HeaderTmpl = NotEditMark + `
package {{.}}

import(
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"
)
`
